import Head from 'next/head'
import Hero from '@/components/Hero'
import BoxSection from '@/components/BoxSection'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Gates Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <Hero />
        <BoxSection />
        <Footer />
      </main>
    </>
  )
}
